#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
$app = new Symfony\Component\Console\Application('Redmine Logger', '3.0.0');
$app->add(new Aleron75\Redlog\Console\LogCommand);
$app->add(new Aleron75\Redlog\Console\ProjectCommand);
$app->run();
