#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$version = '';
$changelog = file_get_contents('CHANGELOG.md');
if ($changelog) {
    preg_match("|\[(\d+\.\d+\.\d+)\]|", $changelog, $matches);
    $version = $matches[1] ?? '';
}

$app = new Symfony\Component\Console\Application('Redmine Logger', $version);
$app->add(new Aleron75\Redlog\Console\LogCommand);
$app->add(new Aleron75\Redlog\Console\ProjectCommand);
$app->run();
